version: '3.8'

services:
  sayit-backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: sayit-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ALLOWED_ORIGINS=*
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./uploads:/app/uploads
      - ./temp:/app/temp
      - backend_logs:/app/logs
    networks:
      - sayit-network
    depends_on:
      - redis
    # ✅ 메모리 및 CPU 제한 추가
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7-alpine
    container_name: sayit-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sayit-network
    # ✅ Redis 메모리 설정 개선
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    # ✅ 메모리 overcommit 설정
    sysctls:
      - vm.overcommit_memory=1
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  backend_logs:
    driver: local
  redis_data:
    driver: local

networks:
  sayit-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: sayit-bridge 