services:
  # Whisper 워커 1 (큐 처리 전용)
  whisper-worker-1:
    build: 
      context: .
      dockerfile: Dockerfile.m2
    container_name: sayit-worker-1-m2
    restart: unless-stopped
    environment:
      - WORKER_ID=Worker-1
      - REDIS_HOST=redis-cluster
      - MAX_CONCURRENT_CHUNKS=4      # ✅ 2→4 (30분 대응)
      - QUEUE_PROCESSING=true        # ✅ 명시적 설정 추가
      - PLATFORM=arm64
      - PYTORCH_ENABLE_MPS_FALLBACK=1
      - OMP_NUM_THREADS=4            # ✅ 3→4 (성능 향상)
      - WORKER_MODE=queue_only
      - CONTAINER_NAME=Worker-1
      - MEMORY_LIMIT=4G              # ✅ 메모리 정보 추가
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2'
        reservations:
          memory: 2G
          cpus: '1'
    volumes:
      - ./uploads:/app/uploads
      - ./temp:/app/temp
      - ./services:/app/services
      - ./routes:/app/routes
      - whisper_cache_1:/tmp/whisper
    networks:
      - sayit-network
    depends_on:
      - redis-cluster

  # Whisper 워커 2 (큐 처리 전용)
  whisper-worker-2:
    build: 
      context: .
      dockerfile: Dockerfile.m2
    container_name: sayit-worker-2-m2
    restart: unless-stopped
    environment:
      - WORKER_ID=Worker-2
      - REDIS_HOST=redis-cluster
      - MAX_CONCURRENT_CHUNKS=4      # ✅ 2→4 (30분 대응)
      - QUEUE_PROCESSING=true        # ✅ 명시적 설정 추가
      - PLATFORM=arm64
      - PYTORCH_ENABLE_MPS_FALLBACK=1
      - OMP_NUM_THREADS=4            # ✅ 3→4 (성능 향상)
      - WORKER_MODE=queue_only
      - CONTAINER_NAME=Worker-2
      - MEMORY_LIMIT=4G
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2'
        reservations:
          memory: 2G
          cpus: '1'
    volumes:
      - ./uploads:/app/uploads
      - ./temp:/app/temp
      - ./services:/app/services
      - ./routes:/app/routes
      - whisper_cache_2:/tmp/whisper
    networks:
      - sayit-network
    depends_on:
      - redis-cluster

  # Whisper 워커 3 (큐 처리 전용)
  whisper-worker-3:
    build: 
      context: .
      dockerfile: Dockerfile.m2
    container_name: sayit-worker-3-m2
    restart: unless-stopped
    environment:
      - WORKER_ID=Worker-3
      - REDIS_HOST=redis-cluster
      - MAX_CONCURRENT_CHUNKS=4      # ✅ 2→4 (30분 대응)
      - QUEUE_PROCESSING=true        # ✅ 명시적 설정 추가
      - PLATFORM=arm64
      - PYTORCH_ENABLE_MPS_FALLBACK=1
      - OMP_NUM_THREADS=4            # ✅ 3→4 (성능 향상)
      - WORKER_MODE=queue_only
      - CONTAINER_NAME=Worker-3
      - MEMORY_LIMIT=4G
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2'
        reservations:
          memory: 2G
          cpus: '1'
    volumes:
      - ./uploads:/app/uploads
      - ./temp:/app/temp
      - ./services:/app/services
      - ./routes:/app/routes
      - whisper_cache_3:/tmp/whisper
    networks:
      - sayit-network
    depends_on:
      - redis-cluster

  # Direct Backend (API 서비스만, 큐 처리 제외)
  direct-backend:
    build: 
      context: .
      dockerfile: Dockerfile.m2
    container_name: sayit-direct-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - WORKER_ID=Direct-Backend
      - REDIS_HOST=redis-cluster
      - MAX_CONCURRENT_CHUNKS=5      # ✅ 4→5 (Direct Backend 성능 향상)
      - PLATFORM=arm64
      - PYTORCH_ENABLE_MPS_FALLBACK=1
      - OMP_NUM_THREADS=5            # ✅ 4→5
      - WORKER_MODE=api_only
      - CONTAINER_NAME=Direct-Backend
      - QUEUE_PROCESSING=false       # ✅ 명시적 설정
      - MEMORY_LIMIT=4G
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2'
        reservations:
          memory: 2G
          cpus: '1'
    volumes:
      - ./uploads:/app/uploads
      - ./temp:/app/temp
      - ./services:/app/services
      - ./routes:/app/routes
      - ./server.js:/app/server.js
      - ./middleware:/app/middleware
      - ./package.json:/app/package.json
      - whisper_cache_direct:/tmp/whisper
    networks:
      - sayit-network
    depends_on:
      - redis-cluster

  # Redis 클러스터 (M2 최적화)
  redis-cluster:
    image: redis:7-alpine
    container_name: sayit-redis-m2
    restart: unless-stopped
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          memory: 3G                 # ✅ 2G→3G (30분 데이터 대응)
          cpus: '1'
        reservations:
          memory: 2G                 # ✅ 1G→2G
          cpus: '0.5'
    volumes:
      - redis_data:/data
    networks:
      - sayit-network
    command: redis-server --maxmemory 2560mb --maxmemory-policy allkeys-lru --appendonly yes --timeout 0 --tcp-keepalive 300
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 모니터링
  monitoring:
    image: prom/node-exporter:latest
    container_name: sayit-monitoring
    restart: unless-stopped
    ports:
      - "9100:9100"
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
    networks:
      - sayit-network

volumes:
  redis_data:
  whisper_cache_1:
  whisper_cache_2:
  whisper_cache_3:
  whisper_cache_direct:

networks:
  sayit-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16 