 version: '3.8'
services:
  direct-backend:
    build: 
      context: .
      dockerfile: Dockerfile.m2
    container_name: sayit-direct-backend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.development  # ✅ 환경변수 파일 사용
    environment:
      # Docker 특화 환경변수만 여기에
      - CONTAINER_NAME=Direct-Backend
      - QUEUE_PROCESSING=false
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev:docker"]
    networks:
      - sayit-network
    depends_on:
      - redis-cluster